#!/bin/bash

if [ -z "$1" ]; then
        echo usage: compressimg [file]
        echo This tool will apply common image optimization techniques to the given file.
        exit
fi


OLDIFS=$IFS #处理防止空格,先备份很重要
IFS=:

OLDSIZE=`ls -l $1 | awk '{ print $5}'`

./pngquant --force --skip-if-larger $1 --output $1

if [ -f $1.tmp ]; then 
    mv $1.tmp $1
fi


NEWSIZE=`ls -l $1 | awk '{ print $5}'`

# show final stats
let RESULT=100-$NEWSIZE*100/$OLDSIZE
echo $1 $NEWSIZE'/'$OLDSIZE ' - ['$RESULT'% COMPRESSED]'


IFS=$OLDIFS #再把IFS挪回来


#pngcrush做PNG的无损压缩，pngquant做PNG的有损压缩。
#pngquant官网 免费，跨平台，有图形化工具，有命令

#pngquant [options] [ncolors] --pngfile
#--help             帮助(简写-h)
#--force            覆盖已存在的导出文件(-f)
#--skip-if-larger   当转换的文件比源文件更小时保存文件
#--output           目标文件路径(-o),与--ext用法相似
#--ext              为导出文件添加一个后缀名，例如--ext new.png
#--quality min-max  为图片转换加一个品质限制，如果转换后的图片比最低品质还低，就不保存，并返回错误码99.取值范围 0-100
#--speed            转换速度与品质的比例。1(最佳品质)，10(速度最快)，默认是3
#
##!/bin/bash
#DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
#cd $DIR
#
#for i in `find . -name "*.png"`
#do
#echo $i
#pngquant  --ext .png  --speed=1  -f $i
#
#done
